name: my first exaample 
on: push # triggers or provide multiple events
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome message
              run: 
                echo "My first Github actions job "
                ls -lrta
                cat README.md
              

            - name : List files 
              run: ls 
            
            - name : read files 
              run: cat readme.md 


